import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("titanic.csv")
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Fare"]=df["Fare"].fillna(df["Fare"].median())
df.drop(columns=['Cabin'],inplace=True)
print(df.isnull().sum())
sns.countplot(x='Survived',data=df)
plt.title("Survival count")
plt.show()
sns.countplot(x='Sex',hue='Survived',data=df)
plt.title("Survival by gender")
plt.show()
sns.countplot(x='Pclass',hue='Survived',data=df)
plt.title("survival by passenger class")
plt.show()
plt.hist(df['Age'],bins=30)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()
plt.hist(df['Fare'],bins=30)
plt.title("Fare Distibution")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True,cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()
df.to_csv("cleaned_titanic.csv",index=False)

